### PR TITLE
Added kernel caching support

### PR DESCRIPTION
**Pull request by dpanfilyonok**
## Proposed Changes

Added support of kernel caching. (_For experimentation only_)

### CODE REVIEW

**Comment by gsvgit** [comment]
Looks good. 
1. Can you provide an example of end-user code? How caching can be enabled/disabled? On which step it should be done?
2. Is this implementation allows one to enable/disable caching for each specific kernel independently?

**Comment by dpanfilyonok** [comment]
Usage:
```fsharp
opencl {

}
|> OpenCLEvaluationContext(IsCachingEnabled = true).RunSync
```
```fsharp
let ctx = OpenCLEvaluationContext()

// without caching
opencl {

}
|>  ctx.RunSync

// with caching
ctx.IsCachingEnabled  <- true
opencl {

}
|>  ctx.RunSync
```
```fsharp
// not sure if this will work
opencl {
  let kernel1 = <@ .. @>
  let kernel2 = <@ .. @>
  
  // with caching
  do! RunCommand kernel1 ... 
  
  // without caching 
  let! ctx = getEvaluationContext
  let clonedContext = ctx.Clone()
  clonedContext.IsCachingEnabled  <- true
  
  do! 
    opencl {
        do! RunCommand kernel2
    } |> clonedContext.RunSync
}
|> OpenCLEvaluationContext().RunSync
```

It should be noted that the proposed solution is suitable for experimentation only. It will crash on caching equal expressions but with different types in it (because string representation of Expr erase types).

**Comment by simpletonDL** [comment]
This solution is suitable for experiments and can also be improved in the future (correct hashing, refactoring). So I think I can make a release

**Comment by gsvgit** [comment]
@simpletonDL well. Please, publish new package.

**Pull request merged**
